--Create the database
CREATE DATABASE IF NOT EXISTS ALX_BOOK_STORE;

USE ALX_BOOK_STORE;

CREATE TABLE AUTHORS(
    AUTHOR_ID INT AUTO_INCREMENT,
    AUTHOR_NAME VARCHAR(100) NOT NULL,
    PRIMARY KEY (AUTHOR ID)
);

CREATE TABLE BOOKS(
    BOOK_ID INT AUTO_INCREMENT,
    TITLE VARCHAR(130) NOT NULL,
    AUTHOR_ID INT,
    PRICE DOUBLE NOT NULL,
    PUBLICATION_DATE DATE NOT NULL,
    PRIMARY KEY (BOOK_ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID) ON DELETE CASCADE
);

CREATE TABLE CUSTORMERS(
    CUSTOMER_ID INT AUTO_INCREMENT,
    CUSTORMER_NAME VARCHAR(215) NOT NULL,
    EMAIL VARCHAR(215) NOT NULL UNIQUE,
    ADDRESS TEXT NOT NULL, 
    PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE ORDERS(
    ORDER_ID INT AUTO_INCREMENT,
    CUSTOMER_ID INT NOT NULL,
    ORDER_DATE DATE NOT NULL,
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID) ON DELETE CASCADE
    
);
CREATE TABLE ORDER_DETAILS (
    ORDERDETAILID INT AUTO_INCREMENT,
    ORDER_ID INT NOT NULL,
    BOOK_ID INT NOT NULL,
    QUANTITY DOUBLE NOT NULL,
    PRIMARY KEY (ORDERDETAILID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID) ON DELETE CASCADE,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID) ON DELETE CASCADE
);