--Use the alx_book_store database
USE ALX_BOOK_STORE;

CREATE TABLE IF NOT EXIST AUTHORS (
    AUTHOR_ID INT AUTO_INCREMENT,
    AUTHOR_NAME VARCHAR(125) NOT NULL,
    PRIMARY KEY (AUTHOR_ID)
)

CREATE TABLE IF NOT EXIST BOOKS(
    BOOK_ID INT AUTO_INCREMENT,
    TITLE VARCHAR(130) NOT NULL,
    AUTHOR_ID INT NOT NULL,
    PRICE DOUBLE NOT NULL,
    PUBLICATION_DATE DATE NOT NULL,
    PRIMARY KEY (BOOK_ID),
    FOREIGN KYE (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID) ON DELETE CASCADE
)

CREATE TABLE IF NOT EXIST CUSTOMERS(
    CUSTOMER_ID INT AUTO_INCREMENT,
    CUSTOMER_NAMER VARCHAR(215) NOT NULL,
    EMAIL VARCHAR(215) NOT NULL UNIQUE,
    ADDRESS TEXT NOT NULL,
    PRIMARY KEY (CUSTOMER_ID)
)

CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID INT AUTO_INCREMENT,
    CUSTOMER_ID INT NOT NULL,
    ORDER_DATE DATE NOT NULL,
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS ORDER_DETAILS (
    ORDERDETAILID INT AUTO_INCREMENT,
    ORDER_ID INT NOT NULL,
    BOOK_ID INT NOT NULL,
    QUANTITY DOUBLE NOT NULL,
    PRIMARY KEY (ORDERDETAILID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID) ON DELETE CASCADE,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID) ON DELETE CASCADE
);